# Extension configuration file.
# Visit the "Extension configuration file (extension.toml)" section for more details:
# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html
#

[core]
reloadable = true
order = 0

[package]
version = "0.1.0"
category = "graph"
title = "Pow Camera Telelop"
authors = ["Titiwat Be Munintravong"]
keywords = ["omnigraph node","ros2","teleop","camera"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.graph" = {}
"omni.graph.tools" = {}

# define the Python module that the extension provides
[[python.module]]
name = "pow.camera.teleop_ros"

[settings]
exts."pow.camera.teleop_ros".timeout = 5

